package com.github.JAA2M.Module;

public record NamedConstant(/*DWORD*/ int id, NamedConstantCategories category, String name, String interactiveName, String description/*, Value val*/) {

    public static final NamedConstant[][] g_NamedConstants = new NamedConstant[][]{
            // INVALID
            {},
            // INT
            {
                //Relationship
                new NamedConstant(1, NamedConstantCategories.RELATIONSHIP, "Love Points", "LOVE", "Love points"/* Value.of(0) */),
                new NamedConstant(2, NamedConstantCategories.RELATIONSHIP, "Like Points", "LIKE", "Like points"/* Value(1) */),
                new NamedConstant(3, NamedConstantCategories.RELATIONSHIP, "Dislike Points", "DISLIKE", "Dislike points"/* Value(2) */),
                new NamedConstant(4, NamedConstantCategories.RELATIONSHIP, "Hate Points", "HATE", "Hate points"/* Value(3) */),
                //Conversation
                new NamedConstant(5, NamedConstantCategories.CONVERSATIONS, "ENCOURAGE", "ENCOURAGE", "ENCOURAGE"/*Value(ExtClass::ConversationId::ENCOURAGE)*/),
                new NamedConstant(6, NamedConstantCategories.CONVERSATIONS, "CALM", "CALM", "CALM"/*Value(ExtClass::ConversationId::CALM)*/),
                new NamedConstant(7, NamedConstantCategories.CONVERSATIONS, "PRAISE", "PRAISE", "PRAISE"/*Value(ExtClass::ConversationId::PRAISE)*/),
                new NamedConstant(8, NamedConstantCategories.CONVERSATIONS, "GRUMBLE", "GRUMBLE", "GRUMBLE"/*Value(ExtClass::ConversationId::GRUMBLE)*/),
                new NamedConstant(9, NamedConstantCategories.CONVERSATIONS, "APOLOGIZE", "APOLOGIZE", "APOLOGIZE"/*Value(ExtClass::ConversationId::APOLOGIZE)*/),
                new NamedConstant(10, NamedConstantCategories.CONVERSATIONS, "ENCOURAGE_STUDY", "ENCOURAGE_STUDY", "ENCOURAGE_STUDY"/*Value(ExtClass::ConversationId::ENCOURAGE_STUDY)*/),
                new NamedConstant(11, NamedConstantCategories.CONVERSATIONS, "ENCOURAGE_EXERCISE", "ENCOURAGE_EXERCISE", "ENCOURAGE_EXERCISE"/*Value(ExtClass::ConversationId::ENCOURAGE_EXERCISE)*/),
                new NamedConstant(12, NamedConstantCategories.CONVERSATIONS, "ENCOURAGE_CLUB", "ENCOURAGE_CLUB", "ENCOURAGE_CLUB"/*Value(ExtClass::ConversationId::ENCOURAGE_CLUB)*/),
                new NamedConstant(13, NamedConstantCategories.CONVERSATIONS, "ENCOURAGE_GET_ALONG", "ENCOURAGE_GET_ALONG", "ENCOURAGE_GET_ALONG"/*Value(ExtClass::ConversationId::ENCOURAGE_GET_ALONG)*/),
                new NamedConstant(14, NamedConstantCategories.CONVERSATIONS, "REPRIMAND_LEWD", "REPRIMAND_LEWD", "REPRIMAND_LEWD"/*Value(ExtClass::ConversationId::REPRIMAND_LEWD)*/),
                new NamedConstant(15, NamedConstantCategories.CONVERSATIONS, "GOOD_RUMOR", "GOOD_RUMOR", "GOOD_RUMOR"/*Value(ExtClass::ConversationId::GOOD_RUMOR)*/),
                new NamedConstant(16, NamedConstantCategories.CONVERSATIONS, "GET_ALONG_WITH", "GET_ALONG_WITH", "GET_ALONG_WITH"/*Value(ExtClass::ConversationId::GET_ALONG_WITH)*/),
                new NamedConstant(17, NamedConstantCategories.CONVERSATIONS, "I_WANNA_GET_ALONG_WITH", "I_WANNA_GET_ALONG_WITH", "I_WANNA_GET_ALONG_WITH"/*Value(ExtClass::ConversationId::I_WANNA_GET_ALONG_WITH)*/),
                new NamedConstant(18, NamedConstantCategories.CONVERSATIONS, "BAD_RUMOR", "BAD_RUMOR", "BAD_RUMOR"/*Value(ExtClass::ConversationId::BAD_RUMOR)*/),
                new NamedConstant(19, NamedConstantCategories.CONVERSATIONS, "DO_YOU_LIKE", "DO_YOU_LIKE", "DO_YOU_LIKE"/*Value(ExtClass::ConversationId::DO_YOU_LIKE)*/),
                new NamedConstant(20, NamedConstantCategories.CONVERSATIONS, "TALK_LIFE", "TALK_LIFE", "TALK_LIFE"/*Value(ExtClass::ConversationId::TALK_LIFE)*/),
                new NamedConstant(21, NamedConstantCategories.CONVERSATIONS, "TALK_HOBBIES", "TALK_HOBBIES", "TALK_HOBBIES"/*Value(ExtClass::ConversationId::TALK_HOBBIES)*/),
                new NamedConstant(22, NamedConstantCategories.CONVERSATIONS, "TALK_FOOD", "TALK_FOOD", "TALK_FOOD"/*Value(ExtClass::ConversationId::TALK_FOOD)*/),
                new NamedConstant(23, NamedConstantCategories.CONVERSATIONS, "TALK_LOVE", "TALK_LOVE", "TALK_LOVE"/*Value(ExtClass::ConversationId::TALK_LOVE)*/),
                new NamedConstant(24, NamedConstantCategories.CONVERSATIONS, "TALK_LEWD", "TALK_LEWD", "TALK_LEWD"/*Value(ExtClass::ConversationId::TALK_LEWD)*/),
                new NamedConstant(25, NamedConstantCategories.CONVERSATIONS, "STUDY_TOGETHER", "STUDY_TOGETHER", "STUDY_TOGETHER"/*Value(ExtClass::ConversationId::STUDY_TOGETHER)*/),
                new NamedConstant(26, NamedConstantCategories.CONVERSATIONS, "EXERCISE_TOGETHER", "EXERCISE_TOGETHER", "EXERCISE_TOGETHER"/*Value(ExtClass::ConversationId::EXERCISE_TOGETHER)*/),
                new NamedConstant(27, NamedConstantCategories.CONVERSATIONS, "CLUB_TOGETHER", "CLUB_TOGETHER", "CLUB_TOGETHER"/*Value(ExtClass::ConversationId::CLUB_TOGETHER)*/),
                new NamedConstant(28, NamedConstantCategories.CONVERSATIONS, "MASSAGE", "MASSAGE", "MASSAGE"/*Value(ExtClass::ConversationId::MASSAGE)*/),
                new NamedConstant(29, NamedConstantCategories.CONVERSATIONS, "GOTO_CLASS", "GOTO_CLASS", "GOTO_CLASS"/*Value(ExtClass::ConversationId::GOTO_CLASS)*/),
                new NamedConstant(30, NamedConstantCategories.CONVERSATIONS, "LUNCH_TOGETHER", "LUNCH_TOGETHER", "LUNCH_TOGETHER" /*Value(ExtClass::ConversationId::LUNCH_TOGETHER)*/),
                new NamedConstant(31, NamedConstantCategories.CONVERSATIONS, "TEA_TOGETHER", "TEA_TOGETHER", "TEA_TOGETHER"/*Value(ExtClass::ConversationId::TEA_TOGETHER)*/),
                new NamedConstant(32, NamedConstantCategories.CONVERSATIONS, "GO_HOME_TOGETHER", "GO_HOME_TOGETHER", "GO_HOME_TOGETHER"/*Value(ExtClass::ConversationId::GO_HOME_TOGETHER)*/),
                new NamedConstant(33, NamedConstantCategories.CONVERSATIONS, "GO_PLAY_TOGETHER", "GO_PLAY_TOGETHER", "GO_PLAY_TOGETHER"/*Value(ExtClass::ConversationId::GO_PLAY_TOGETHER)*/),
                new NamedConstant(34, NamedConstantCategories.CONVERSATIONS, "GO_EAT_TOGETHER", "GO_EAT_TOGETHER", "GO_EAT_TOGETHER"/*Value(ExtClass::ConversationId::GO_EAT_TOGETHER)*/),
                new NamedConstant(35, NamedConstantCategories.CONVERSATIONS, "GO_KARAOKE_TOGETHER", "GO_KARAOKE_TOGETHER", "GO_KARAOKE_TOGETHER"/*Value(ExtClass::ConversationId::GO_KARAOKE_TOGETHER)*/),
                new NamedConstant(36, NamedConstantCategories.CONVERSATIONS, "STUDY_HOME", "STUDY_HOME", "STUDY_HOME"/*Value(ExtClass::ConversationId::STUDY_HOME)*/),
                new NamedConstant(37, NamedConstantCategories.CONVERSATIONS, "STUDY_HOME_H", "STUDY_HOME_H", "STUDY_HOME_H"/*Value(ExtClass::ConversationId::STUDY_HOME_H)*/),
                new NamedConstant(38, NamedConstantCategories.CONVERSATIONS, "INSULT", "INSULT", "INSULT"/*Value(ExtClass::ConversationId::INSULT)*/),
                new NamedConstant(39, NamedConstantCategories.CONVERSATIONS, "FIGHT", "FIGHT", "FIGHT"/*Value(ExtClass::ConversationId::FIGHT)*/),
                new NamedConstant(40, NamedConstantCategories.CONVERSATIONS, "FORCE_IGNORE", "FORCE_IGNORE", "FORCE_IGNORE"/*Value(ExtClass::ConversationId::FORCE_IGNORE)*/),
                new NamedConstant(41, NamedConstantCategories.CONVERSATIONS, "FORCE_SHOW_THAT", "FORCE_SHOW_THAT", "FORCE_SHOW_THAT"/*Value(ExtClass::ConversationId::FORCE_SHOW_THAT)*/),
                new NamedConstant(42, NamedConstantCategories.CONVERSATIONS, "FORCE_PUT_THIS_ON", "FORCE_PUT_THIS_ON", "FORCE_PUT_THIS_ON"/*Value(ExtClass::ConversationId::FORCE_PUT_THIS_ON)*/),
                new NamedConstant(43, NamedConstantCategories.CONVERSATIONS, "FORCE_H", "FORCE_H", "FORCE_H"/*Value(ExtClass::ConversationId::FORCE_H)*/),
                new NamedConstant(44, NamedConstantCategories.CONVERSATIONS, "MAKE_JOIN_CLUB", "MAKE_JOIN_CLUB", "MAKE_JOIN_CLUB"/*Value(ExtClass::ConversationId::MAKE_JOIN_CLUB)*/),
                new NamedConstant(45, NamedConstantCategories.CONVERSATIONS, "ASK_DATE", "ASK_DATE", "ASK_DATE"/*Value(ExtClass::ConversationId::ASK_DATE)*/),
                new NamedConstant(46, NamedConstantCategories.CONVERSATIONS, "CONFESS", "CONFESS", "CONFESS"/*Value(ExtClass::ConversationId::CONFESS)*/),
                new NamedConstant(47, NamedConstantCategories.CONVERSATIONS, "ASK_COUPLE", "ASK_COUPLE", "ASK_COUPLE"/*Value(ExtClass::ConversationId::ASK_COUPLE)*/),
                new NamedConstant(48, NamedConstantCategories.CONVERSATIONS, "ASK_BREAKUP", "ASK_BREAKUP", "ASK_BREAKUP"/*Value(ExtClass::ConversationId::ASK_BREAKUP)*/),
                new NamedConstant(49, NamedConstantCategories.CONVERSATIONS, "HEADPAT", "HEADPAT", "HEADPAT"/*Value(ExtClass::ConversationId::HEADPAT)*/),
                new NamedConstant(50, NamedConstantCategories.CONVERSATIONS, "HUG", "HUG", "HUG"/*Value(ExtClass::ConversationId::HUG)*/),
                new NamedConstant(51, NamedConstantCategories.CONVERSATIONS, "KISS", "KISS", "KISS"/*Value(ExtClass::ConversationId::KISS)*/),
                new NamedConstant(52, NamedConstantCategories.CONVERSATIONS, "TOUCH", "TOUCH", "TOUCH"/*Value(ExtClass::ConversationId::TOUCH)*/),
                new NamedConstant(53, NamedConstantCategories.CONVERSATIONS, "NORMAL_H", "NORMAL_H", "NORMAL_H"/*Value(ExtClass::ConversationId::NORMAL_H)*/),
                new NamedConstant(54, NamedConstantCategories.CONVERSATIONS, "FOLLOW_ME", "FOLLOW_ME", "FOLLOW_ME"/*Value(ExtClass::ConversationId::FOLLOW_ME)*/),
                new NamedConstant(55, NamedConstantCategories.CONVERSATIONS, "GO_AWAY", "GO_AWAY", "GO_AWAY"/*Value(ExtClass::ConversationId::GO_AWAY)*/),
                new NamedConstant(56, NamedConstantCategories.CONVERSATIONS, "COME_TO", "COME_TO", "COME_TO"/*Value(ExtClass::ConversationId::COME_TO)*/),
                new NamedConstant(57, NamedConstantCategories.CONVERSATIONS, "NEVERMIND", "NEVERMIND", "NEVERMIND"/*Value(ExtClass::ConversationId::NEVERMIND)*/),
                new NamedConstant(58, NamedConstantCategories.CONVERSATIONS, "MINNA_STUDY", "MINNA_STUDY", "MINNA_STUDY"/*Value(ExtClass::ConversationId::MINNA_STUDY)*/),
                new NamedConstant(59, NamedConstantCategories.CONVERSATIONS, "MINNA_SPORTS", "MINNA_SPORTS", "MINNA_SPORTS"/*Value(ExtClass::ConversationId::MINNA_SPORTS)*/),
                new NamedConstant(60, NamedConstantCategories.CONVERSATIONS, "MINNA_CLUB", "MINNA_CLUB", "MINNA_CLUB"/*Value(ExtClass::ConversationId::MINNA_CLUB)*/),
                new NamedConstant(61, NamedConstantCategories.CONVERSATIONS, "MINNA_LUNCH", "MINNA_LUNCH", "MINNA_LUNCH"/*Value(ExtClass::ConversationId::MINNA_LUNCH)*/),
                new NamedConstant(62, NamedConstantCategories.CONVERSATIONS, "MINNA_REST", "MINNA_REST", "MINNA_REST"/*Value(ExtClass::ConversationId::MINNA_REST)*/),
                new NamedConstant(63, NamedConstantCategories.CONVERSATIONS, "MINNA_EAT", "MINNA_EAT", "MINNA_EAT"/*Value(ExtClass::ConversationId::MINNA_EAT)*/),
                new NamedConstant(64, NamedConstantCategories.CONVERSATIONS, "MINNA_KARAOKE", "MINNA_KARAOKE", "MINNA_KARAOKE"/*Value(ExtClass::ConversationId::MINNA_KARAOKE)*/),
                new NamedConstant(65, NamedConstantCategories.CONVERSATIONS, "MINNA_BE_FRIENDLY", "MINNA_BE_FRIENDLY", "MINNA_BE_FRIENDLY"/*Value(ExtClass::ConversationId::MINNA_BE_FRIENDLY)*/),
                new NamedConstant(66, NamedConstantCategories.CONVERSATIONS, "MINNA_COME", "MINNA_COME", "MINNA_COME"/*Value(ExtClass::ConversationId::MINNA_COME)*/),
                new NamedConstant(67, NamedConstantCategories.CONVERSATIONS, "INTERRUPT_COMPETE", "INTERRUPT_COMPETE", "INTERRUPT_COMPETE"/*Value(ExtClass::ConversationId::INTERRUPT_COMPETE)*/),
                new NamedConstant(68, NamedConstantCategories.CONVERSATIONS, "INTERRUPT_WHAT_ARE_YOU_DOING", "INTERRUPT_WHAT_ARE_YOU_DOING", "INTERRUPT_WHAT_ARE_YOU_DOING"/*Value(ExtClass::ConversationId::INTERRUPT_WHAT_ARE_YOU_DOING)*/),
                new NamedConstant(69, NamedConstantCategories.CONVERSATIONS, "INTERRUPT_STOP_QUARREL", "INTERRUPT_STOP_QUARREL", "INTERRUPT_STOP_QUARREL"/*Value(ExtClass::ConversationId::INTERRUPT_STOP_QUARREL)*/),
                new NamedConstant(70, NamedConstantCategories.CONVERSATIONS, "H_END", "H_END", "H_END"/*Value(ExtClass::ConversationId::H_END)*/),
                new NamedConstant(71, NamedConstantCategories.CONVERSATIONS, "H_NOTE", "H_NOTE", "H_NOTE"/*Value(ExtClass::ConversationId::H_NOTE)*/),
                new NamedConstant(72, NamedConstantCategories.CONVERSATIONS, "TRY_3P", "TRY_3P", "TRY_3P"/*Value(ExtClass::ConversationId::TRY_3P)*/),
                new NamedConstant(73, NamedConstantCategories.CONVERSATIONS, "REQUEST_MASSAGE", "REQUEST_MASSAGE", "REQUEST_MASSAGE"/*Value(ExtClass::ConversationId::REQUEST_MASSAGE)*/),
                new NamedConstant(74, NamedConstantCategories.CONVERSATIONS, "REQUEST_KISS", "REQUEST_KISS", "REQUEST_KISS"/*Value(ExtClass::ConversationId::REQUEST_KISS)*/),
                new NamedConstant(75, NamedConstantCategories.CONVERSATIONS, "REQUEST_HUG", "REQUEST_HUG", "REQUEST_HUG"/*Value(ExtClass::ConversationId::REQUEST_HUG)*/),
                new NamedConstant(76, NamedConstantCategories.CONVERSATIONS, "SKIP_CLASS", "SKIP_CLASS", "SKIP_CLASS"/*Value(ExtClass::ConversationId::SKIP_CLASS)*/),
                new NamedConstant(77, NamedConstantCategories.CONVERSATIONS, "SKIP_CLASS_H", "SKIP_CLASS_H", "SKIP_CLASS_H"/*Value(ExtClass::ConversationId::SKIP_CLASS_H)*/),
                new NamedConstant(78, NamedConstantCategories.CONVERSATIONS, "SKIP_CLASS_SURPRISE_H", "SKIP_CLASS_SURPRISE_H", "SKIP_CLASS_SURPRISE_H"/*Value(ExtClass::ConversationId::SKIP_CLASS_SURPRISE_H)*/),
                new NamedConstant(79, NamedConstantCategories.CONVERSATIONS, "DID_YOU_HAVE_H", "DID_YOU_HAVE_H", "DID_YOU_HAVE_H"/*Value(ExtClass::ConversationId::DID_YOU_HAVE_H)*/),
                new NamedConstant(80, NamedConstantCategories.CONVERSATIONS, "SHOW_UNDERWEAR", "SHOW_UNDERWEAR", "SHOW_UNDERWEAR"/*Value(ExtClass::ConversationId::SHOW_UNDERWEAR)*/),
                new NamedConstant(81, NamedConstantCategories.CONVERSATIONS, "DID_YOU_HAVE_H_WITH", "DID_YOU_HAVE_H_WITH", "DID_YOU_HAVE_H_WITH"/*Value(ExtClass::ConversationId::DID_YOU_HAVE_H_WITH)*/),
                new NamedConstant(82, NamedConstantCategories.CONVERSATIONS, "EXCHANGE_ITEMS", "EXCHANGE_ITEMS", "EXCHANGE_ITEMS"/*Value(ExtClass::ConversationId::EXCHANGE_ITEMS)*/),
                new NamedConstant(83, NamedConstantCategories.CONVERSATIONS, "LEWD_PROMISE", "LEWD_PROMISE", "LEWD_PROMISE"/*Value(ExtClass::ConversationId::LEWD_PROMISE)*/),
                new NamedConstant(84, NamedConstantCategories.CONVERSATIONS, "LEWD_REWARD", "LEWD_REWARD", "LEWD_REWARD"/*Value(ExtClass::ConversationId::LEWD_REWARD)*/),
                new NamedConstant(85, NamedConstantCategories.CONVERSATIONS, "TOGETHER_FOREVER", "TOGETHER_FOREVER", "TOGETHER_FOREVER"/*Value(ExtClass::ConversationId::TOGETHER_FOREVER)*/),
                new NamedConstant(86, NamedConstantCategories.CONVERSATIONS, "MURDER", "MURDER", "MURDER"/*Value(ExtClass::ConversationId::MURDER)*/),
                new NamedConstant(87, NamedConstantCategories.CONVERSATIONS, "SLAP", "SLAP", "SLAP"/*Value(ExtClass::ConversationId::SLAP)*/),
                new NamedConstant(88, NamedConstantCategories.CONVERSATIONS, "GOOD_MORNING_KISS", "GOOD_MORNING_KISS", "GOOD_MORNING_KISS"/*Value(ExtClass::ConversationId::GOOD_MORNING_KISS)*/),
                new NamedConstant(89, NamedConstantCategories.CONVERSATIONS, "GOOD_BYE_KISS", "GOOD_BYE_KISS", "GOOD_BYE_KISS"/*Value(ExtClass::ConversationId::GOOD_BYE_KISS)*/),
                new NamedConstant(90, NamedConstantCategories.CONVERSATIONS, "NO_PROMPT_KISS", "NO_PROMPT_KISS", "NO_PROMPT_KISS"/*Value(ExtClass::ConversationId::NO_PROMPT_KISS)*/),
                new NamedConstant(91, NamedConstantCategories.CONVERSATIONS, "FORCE_BREAKUP", "FORCE_BREAKUP", "FORCE_BREAKUP"/*Value(ExtClass::ConversationId::FORCE_BREAKUP)*/),
                new NamedConstant(92, NamedConstantCategories.CONVERSATIONS, "REVEAL_PREGNANCY", "REVEAL_PREGNANCY", "REVEAL_PREGNANCY"/*Value(ExtClass::ConversationId::REVEAL_PREGNANCY)*/),
                new NamedConstant(93, NamedConstantCategories.CONVERSATIONS, "I_WILL_CHEAT", "I_WILL_CHEAT", "I_WILL_CHEAT"/*Value(ExtClass::ConversationId::I_WILL_CHEAT)*/),
                new NamedConstant(94, NamedConstantCategories.CONVERSATIONS, "EXPLOITABLE_LINE", "EXPLOITABLE_LINE", "EXPLOITABLE_LINE"/*Value(ExtClass::ConversationId::EXPLOITABLE_LINE)*/),
                new NamedConstant(95, NamedConstantCategories.CONVERSATIONS, "STOP_FOLLOWING", "STOP_FOLLOWING", "STOP_FOLLOWING"/*Value(ExtClass::ConversationId::STOP_FOLLOWING)*/),
                new NamedConstant(96, NamedConstantCategories.CONVERSATIONS, "MURDER_NOTICE", "MURDER_NOTICE", "MURDER_NOTICE"/*Value(ExtClass::ConversationId::MURDER_NOTICE)*/),
                new NamedConstant(97, NamedConstantCategories.CONVERSATIONS, "SOMEONE_LIKES_YOU", "SOMEONE_LIKES_YOU", "SOMEONE_LIKES_YOU"/*Value(ExtClass::ConversationId::SOMEONE_LIKES_YOU)*/),
                new NamedConstant(98, NamedConstantCategories.CONVERSATIONS, "SOMEONE_GOT_CONFESSED_TO", "SOMEONE_GOT_CONFESSED_TO", "SOMEONE_GOT_CONFESSED_TO"/*Value(ExtClass::ConversationId::SOMEONE_GOT_CONFESSED_TO)*/),
                new NamedConstant(99, NamedConstantCategories.CONVERSATIONS, "DID_YOU_DATE_SOMEONE", "DID_YOU_DATE_SOMEONE", "DID_YOU_DATE_SOMEONE"/*Value(ExtClass::ConversationId::DID_YOU_DATE_SOMEONE)*/),
                new NamedConstant(100, NamedConstantCategories.CONVERSATIONS, "I_SAW_SOMEONE_HAVE_H", "I_SAW_SOMEONE_HAVE_H", "I_SAW_SOMEONE_HAVE_H"/*Value(ExtClass::ConversationId::I_SAW_SOMEONE_HAVE_H)*/),
                new NamedConstant(101, NamedConstantCategories.CONVERSATIONS, "GUST_OF_WIND", "GUST_OF_WIND", "GUST_OF_WIND"/*Value(ExtClass::ConversationId::GUST_OF_WIND)*/),
                new NamedConstant(102, NamedConstantCategories.CONVERSATIONS, "DO_NOT_GET_INVOLVED", "DO_NOT_GET_INVOLVED", "DO_NOT_GET_INVOLVED"/*Value(ExtClass::ConversationId::DO_NOT_GET_INVOLVED)*/),
                new NamedConstant(103, NamedConstantCategories.CONVERSATIONS, "SHAMELESS", "SHAMELESS", "SHAMELESS"/*Value(ExtClass::ConversationId::SHAMELESS)*/),
                new NamedConstant(104, NamedConstantCategories.CONVERSATIONS, "NO_PROMPT_H", "NO_PROMPT_H", "NO_PROMPT_H"/*Value(ExtClass::ConversationId::NO_PROMPT_H)*/),
                new NamedConstant(105, NamedConstantCategories.CONVERSATIONS, "AFTER_DATE_H", "AFTER_DATE_H", "AFTER_DATE_H"/*Value(ExtClass::ConversationId::AFTER_DATE_H)*/),
                new NamedConstant(106, NamedConstantCategories.CONVERSATIONS, "FOLLOW_ME_H", "FOLLOW_ME_H", "FOLLOW_ME_H"/*Value(ExtClass::ConversationId::FOLLOW_ME_H)*/),
                new NamedConstant(107, NamedConstantCategories.CONVERSATIONS, "DATE_GREETING", "DATE_GREETING", "DATE_GREETING"/*Value(ExtClass::ConversationId::DATE_GREETING)*/),
                new NamedConstant(108, NamedConstantCategories.CONVERSATIONS, "CHANGE_CLOTHES", "CHANGE_CLOTHES", "CHANGE_CLOTHES"/*Value(ExtClass::ConversationId::CHANGE_CLOTHES)*/),
                new NamedConstant(109, NamedConstantCategories.CONVERSATIONS, "STALK", "STALK", "STALK"/*Value(ExtClass::ConversationId::STALK)*/),
                new NamedConstant(110, NamedConstantCategories.CONVERSATIONS, "STALK_FROM_AFAR", "STALK_FROM_AFAR", "STALK_FROM_AFAR"/*Value(ExtClass::ConversationId::STALK_FROM_AFAR)*/),
                new NamedConstant(111, NamedConstantCategories.CONVERSATIONS, "DO_STUDY", "DO_STUDY", "DO_STUDY"/*Value(ExtClass::ConversationId::DO_STUDY)*/),
                new NamedConstant(112, NamedConstantCategories.CONVERSATIONS, "DO_EXERCISE", "DO_EXERCISE", "DO_EXERCISE"/*Value(ExtClass::ConversationId::DO_EXERCISE)*/),
                new NamedConstant(113, NamedConstantCategories.CONVERSATIONS, "DO_CLUB", "DO_CLUB", "DO_CLUB"/*Value(ExtClass::ConversationId::DO_CLUB)*/),
                new NamedConstant(114, NamedConstantCategories.CONVERSATIONS, "BREAK_CHAT", "BREAK_CHAT", "BREAK_CHAT"/*Value(ExtClass::ConversationId::BREAK_CHAT)*/),
                new NamedConstant(115, NamedConstantCategories.CONVERSATIONS, "BREAK_H", "BREAK_H", "BREAK_H"/*Value(ExtClass::ConversationId::BREAK_H)*/),
                new NamedConstant(116, NamedConstantCategories.CONVERSATIONS, "TEST_3P", "TEST_3P", "TEST_3P"/*Value(ExtClass::ConversationId::TEST_3P)*/),
                new NamedConstant(117, NamedConstantCategories.CONVERSATIONS, "MINNA_H", "MINNA_H", "MINNA_H"/*Value(ExtClass::ConversationId::MINNA_H)*/),
                //Trait
                new NamedConstant(118, NamedConstantCategories.TRAIT, "EASYGOING", "EASYGOING", "EASYGOING"/*Value(0)*/),
                new NamedConstant(119, NamedConstantCategories.TRAIT, "AFFABLE", "AFFABLE", "AFFABLE"/*Value(1)*/),
                new NamedConstant(120, NamedConstantCategories.TRAIT, "BAD_WITH_GUYS", "BAD_WITH_GUYS", "BAD_WITH_GUYS"/*Value(2)*/),
                new NamedConstant(121, NamedConstantCategories.TRAIT, "BAD_WITH_GIRLS", "BAD_WITH_GIRLS", "BAD_WITH_GIRLS"/*Value(3)*/),
                new NamedConstant(122, NamedConstantCategories.TRAIT, "CHARMING", "CHARMING", "CHARMING"/*Value(4)*/),
                new NamedConstant(123, NamedConstantCategories.TRAIT, "TSUNDERE", "TSUNDERE", "TSUNDERE"/*Value(5)*/),
                new NamedConstant(124, NamedConstantCategories.TRAIT, "CHIVALROUS", "CHIVALROUS", "CHIVALROUS"/*Value(6)*/),
                new NamedConstant(125, NamedConstantCategories.TRAIT, "TRENDY", "TRENDY", "TRENDY"/*Value(7)*/),
                new NamedConstant(126, NamedConstantCategories.TRAIT, "OBEDIENT", "OBEDIENT", "OBEDIENT"/*Value(8)*/),
                new NamedConstant(127, NamedConstantCategories.TRAIT, "POSITIVE", "POSITIVE", "POSITIVE"/*Value(9)*/),
                new NamedConstant(128, NamedConstantCategories.TRAIT, "SHY", "SHY", "SHY"/*Value(10)*/),
                new NamedConstant(129, NamedConstantCategories.TRAIT, "JEALOUS", "JEALOUS", "JEALOUS"/*Value(11)*/),
                new NamedConstant(130, NamedConstantCategories.TRAIT, "MELANCHOLY", "MELANCHOLY", "MELANCHOLY"/*Value(12)*/),
                new NamedConstant(131, NamedConstantCategories.TRAIT, "PERVERTED", "PERVERTED", "PERVERTED"/*Value(13)*/),
                new NamedConstant(132, NamedConstantCategories.TRAIT, "SERIOUS", "SERIOUS", "SERIOUS"/*Value(14)*/),
                new NamedConstant(133, NamedConstantCategories.TRAIT, "CALM", "CALM", "CALM"/*Value(15)*/),
                new NamedConstant(134, NamedConstantCategories.TRAIT, "IMPULSIVE", "IMPULSIVE", "IMPULSIVE"/*Value(16)*/),
                new NamedConstant(135, NamedConstantCategories.TRAIT, "ABSENTMINDED", "ABSENTMINDED", "ABSENTMINDED"/*Value(17)*/),
                new NamedConstant(136, NamedConstantCategories.TRAIT, "VIOLENT", "VIOLENT", "VIOLENT"/*Value(18)*/),
                new NamedConstant(137, NamedConstantCategories.TRAIT, "PASSIVE", "PASSIVE", "PASSIVE"/*Value(19)*/),
                new NamedConstant(138, NamedConstantCategories.TRAIT, "MEDDLESOME", "MEDDLESOME", "MEDDLESOME"/*Value(20)*/),
                new NamedConstant(139, NamedConstantCategories.TRAIT, "CLASS_PREZ", "CLASS_PREZ", "CLASS_PREZ"/*Value(21)*/),
                new NamedConstant(140, NamedConstantCategories.TRAIT, "CHATTY", "CHATTY", "CHATTY"/*Value(22)*/),
                new NamedConstant(141, NamedConstantCategories.TRAIT, "ALWAYS_HUNGRY", "ALWAYS_HUNGRY", "ALWAYS_HUNGRY"/*Value(23)*/),
                new NamedConstant(142, NamedConstantCategories.TRAIT, "ROMANTIC", "ROMANTIC", "ROMANTIC"/*Value(24)*/),
                new NamedConstant(143, NamedConstantCategories.TRAIT, "SINGLEMINDED", "SINGLEMINDED", "SINGLEMINDED"/*Value(25)*/),
                new NamedConstant(144, NamedConstantCategories.TRAIT, "INDECISIVE", "INDECISIVE", "INDECISIVE"/*Value(26)*/),
                new NamedConstant(145, NamedConstantCategories.TRAIT, "COMPETITIVE", "COMPETITIVE", "COMPETITIVE"/*Value(27)*/),
                new NamedConstant(146, NamedConstantCategories.TRAIT, "SCHEMING", "SCHEMING", "SCHEMING"/*Value(28)*/),
                new NamedConstant(147, NamedConstantCategories.TRAIT, "DILIGENT", "DILIGENT", "DILIGENT"/*Value(29)*/),
                new NamedConstant(148, NamedConstantCategories.TRAIT, "WILD", "WILD", "WILD"/*Value(30)*/),
                new NamedConstant(149, NamedConstantCategories.TRAIT, "MASOCHIST", "MASOCHIST", "MASOCHIST"/*Value(31)*/),
                new NamedConstant(150, NamedConstantCategories.TRAIT, "SWEATY", "SWEATY", "SWEATY"/*Value(32)*/),
                new NamedConstant(151, NamedConstantCategories.TRAIT, "EVIL", "EVIL", "EVIL"/*Value(33)*/),
                new NamedConstant(152, NamedConstantCategories.TRAIT, "DEAF", "DEAF", "DEAF"/*Value(34)*/),
                new NamedConstant(153, NamedConstantCategories.TRAIT, "EXPLOITABLE", "EXPLOITABLE", "EXPLOITABLE"/*Value(35)*/),
                new NamedConstant(154, NamedConstantCategories.TRAIT, "ASEXUAL", "ASEXUAL", "ASEXUAL"/*Value(36)*/),
                new NamedConstant(155, NamedConstantCategories.TRAIT, "LUCKY", "LUCKY", "LUCKY"/*Value(37)*/),
                new NamedConstant(156, NamedConstantCategories.TRAIT, "RAINBOW", "RAINBOW", "RAINBOW"/*Value(38)*/),
                //Period
                new NamedConstant(157, NamedConstantCategories.TIME_PERIOD, "MORNING_ROOM", "MORNING_ROOM", "MORNING_ROOM"/*Value(ExtClass::PeriodId::MORNING_ROOM)*/),
                new NamedConstant(158, NamedConstantCategories.TIME_PERIOD, "MORNING_SCHOOL", "MORNING_SCHOOL", "MORNING_SCHOOL"/*Value(ExtClass::PeriodId::MORNING_SCHOOL)*/),
                new NamedConstant(159, NamedConstantCategories.TIME_PERIOD, "FIRST_LESSON", "FIRST_LESSON", "FIRST_LESSON"/*Value(ExtClass::PeriodId::FIRST_LESSON)*/),
                new NamedConstant(160, NamedConstantCategories.TIME_PERIOD, "FIRST_BREAK", "FIRST_BREAK", "FIRST_BREAK"/*Value(ExtClass::PeriodId::FIRST_BREAK)*/),
                new NamedConstant(161, NamedConstantCategories.TIME_PERIOD, "SPORTS", "SPORTS", "SPORTS"/*Value(ExtClass::PeriodId::SPORTS)*/),
                new NamedConstant(162, NamedConstantCategories.TIME_PERIOD, "SECOND_BREAK", "SECOND_BREAK", "SECOND_BREAK"/*Value(ExtClass::PeriodId::SECOND_BREAK)*/),
                new NamedConstant(163, NamedConstantCategories.TIME_PERIOD, "CLUB", "CLUB", "CLUB"/*Value(ExtClass::PeriodId::CLUB)*/),
                new NamedConstant(164, NamedConstantCategories.TIME_PERIOD, "EVENING_SCHOOL", "EVENING_SCHOOL", "EVENING_SCHOOL"/*Value(ExtClass::PeriodId::EVENING_SCHOOL)*/),
                new NamedConstant(165, NamedConstantCategories.TIME_PERIOD, "EVENING_ROOM", "EVENING_ROOM", "EVENING_ROOM"/*Value(ExtClass::PeriodId::EVENING_ROOM)*/),
                new NamedConstant(166, NamedConstantCategories.TIME_PERIOD, "SLEEP", "SLEEP", "SLEEP"/*Value(ExtClass::PeriodId::SLEEP)*/),
                //Time of Day
                new NamedConstant(167, NamedConstantCategories.TIME_DAY, "MONDAY", "MONDAY", "MONDAY"/*Value(ExtClass::DayName::MONDAY)*/),
                new NamedConstant(168, NamedConstantCategories.TIME_DAY, "TUESDAY", "TUESDAY", "TUESDAY"/*Value(ExtClass::DayName::TUESDAY)*/),
                new NamedConstant(169, NamedConstantCategories.TIME_DAY, "WEDNESDAY", "WEDNESDAY", "WEDNESDAY"/*Value(ExtClass::DayName::WEDNESDAY)*/),
                new NamedConstant(170, NamedConstantCategories.TIME_DAY, "THURSDAY", "THURSDAY", "THURSDAY"/*Value(ExtClass::DayName::THURSDAY)*/),
                new NamedConstant(171, NamedConstantCategories.TIME_DAY, "FRIDAY", "FRIDAY", "FRIDAY"/*Value(ExtClass::DayName::FRIDAY)*/),
                new NamedConstant(172, NamedConstantCategories.TIME_DAY, "SATURDAY", "SATURDAY", "SATURDAY"/*Value(ExtClass::DayName::SATURDAY)*/),
                new NamedConstant(173, NamedConstantCategories.TIME_DAY, "SUNDAY", "SUNDAY", "SUNDAY"/*Value(ExtClass::DayName::SUNDAY)*/),
                //Character
                new NamedConstant(174, NamedConstantCategories.CHAR_PREG_RISK, "NORMAL", "NORMAL", "NORMAL"/*Value(ExtClass::PregnancyRisk::PREGRISK_NORMAL)*/),
                new NamedConstant(175, NamedConstantCategories.CHAR_PREG_RISK, "SAFE", "SAFE", "SAFE"/*Value(ExtClass::PregnancyRisk::PREGRISK_SAFE)*/),
                new NamedConstant(176, NamedConstantCategories.CHAR_PREG_RISK, "DANGEROUS", "DANGEROUS", "DANGEROUS"/*Value(ExtClass::PregnancyRisk::PREGRISK_DANGEROUS)*/),
                //Events
                new NamedConstant(177, NamedConstantCategories.EVENT_TYPE, "INVALID", "INVALID", "INVALID"/*Value(Shared::Triggers::Events::INVALID)*/),
                new NamedConstant(178, NamedConstantCategories.EVENT_TYPE, "Clothes Changed", "CLOTHES_CHANGED", "Whenever a character changes clothes, either in the changing room or by entering the next period. (Not yet implemented)"/*Value(Shared::Triggers::Events::CLOTHES_CHANGED)*/),
                new NamedConstant(179, NamedConstantCategories.EVENT_TYPE, "Card Initialized", "CARD_INITIALIZED", "After the AAU Card data was successfully loaded, either because a class containing this card was loaded, or because \n"+ "this card was added to the class roster"/*Value(Shared::Triggers::Events::CARD_INITIALIZED)*/),
                new NamedConstant(180, NamedConstantCategories.EVENT_TYPE, "Card Destroyed", "CARD_DESTROYED", "Before the AAU Card data will be unloaded"/*Value(Shared::Triggers::Events::CARD_DESTROYED)*/),
                new NamedConstant(181, NamedConstantCategories.EVENT_TYPE, "Hi Poly Model Initialized", "HI_POLY_INIT", "Right after the Characters High Poly Model started loading"/*Value(Shared::Triggers::Events::HI_POLY_INIT)*/),
                new NamedConstant(182, NamedConstantCategories.EVENT_TYPE, "Hi Poly Model Loaded", "HI_POLY_END", "Right after the Character High Poly Model finished loading"/*Value(Shared::Triggers::Events::HI_POLY_END)*/),
                new NamedConstant(183, NamedConstantCategories.EVENT_TYPE, "Card Added to Class", "CARD_ADDED", "When a card (including this card) is added to a class, after the CARD_INTIALIZED event is executed"/*Value(Shared::Triggers::Events::CARD_ADDED)*/),
                new NamedConstant(184, NamedConstantCategories.EVENT_TYPE, "A Period Ends", "PERIOD_ENDS", "After a period ends, including lessons themselves"/*Value(Shared::Triggers::Events::PERIOD_ENDS)*/),
                new NamedConstant(185, NamedConstantCategories.EVENT_TYPE, "NPC Answers in Conversation", "NPC_RESPONSE", "Whenever a NPC made a yes/no decision, no matter if towards the PC or another NPC. Triggering Card is the NPC that gives the Answer"/*Value(Shared::Triggers::Events::NPC_RESPONSE)*/),
                new NamedConstant(186, NamedConstantCategories.EVENT_TYPE, "Npc Starts Walking to a Room", "NPC_WALK_TO_ROOM", "Whenever a NPC decides to walk towards a room"/*Value(Shared::Triggers::Events::NPC_WALK_TO_ROOM)*/),
                new NamedConstant(187, NamedConstantCategories.EVENT_TYPE, "Npc Wants to do something with no Target", "NPC_WANT_ACTION_NOTARGET", "Whenever a NPC decides to do an action that does not require another Npc"/*Value(Shared::Triggers::Events::NPC_WANT_ACTION_NOTARGET)*/),
                new NamedConstant(188, NamedConstantCategories.EVENT_TYPE, "Npc Wants to Talk With Someone", "NPC_WANT_TALK_WITH", "Whenever a NPC decides to talk to someone"/*Value(Shared::Triggers::Events::NPC_WANT_TALK_WITH)*/),
                new NamedConstant(189, NamedConstantCategories.EVENT_TYPE, "Npc Wants to Talk With Someone About Someone", "NPC_WANT_TALK_WITH_ABOUT", "Whenever a NPC decides to talk to someone about someone else, such as spreading rumors or asking for opinion about someone"/*Value(Shared::Triggers::Events::NPC_WANT_TALK_WITH_ABOUT)*/),
                new NamedConstant(190, NamedConstantCategories.EVENT_TYPE, "PC conversation state updated", "PC_CONVERSATION_STATE_UPDATED", "PC Conversation state updated"/*Value(Shared::Triggers::Events::PC_CONVERSATION_STATE_UPDATED)*/),
                new NamedConstant(298, NamedConstantCategories.EVENT_TYPE, "Pc Answers in a Conversation", "PC_RESPONSE", "Pc Answers in a Conversation"/*Value(Shared::Triggers::Events::PC_RESPONSE)*/),
                new NamedConstant(299, NamedConstantCategories.EVENT_TYPE, "PC conversation line updated", "PC_CONVERSATION_LINE_UPDATED", "PC conversation line updated"/*Value(Shared::Triggers::Events::PC_CONVERSATION_LINE_UPDATED)*/),
                new NamedConstant(300, NamedConstantCategories.EVENT_TYPE, "Card Changes Room", "ROOM_CHANGE", "Card Changes Room"/*Value(Shared::Triggers::Events::ROOM_CHANGE)*/),
                new NamedConstant(301, NamedConstantCategories.EVENT_TYPE, "Key Press", "KEY_PRESS", "Key Press"/*Value(Shared::Triggers::Events::KEY_PRESS)*/),
                new NamedConstant(302, NamedConstantCategories.EVENT_TYPE, "H Position Change", "HPOSITION_CHANGE", "H Position Change"/*Value(Shared::Triggers::Events::HPOSITION_CHANGE)*/),
                new NamedConstant(303, NamedConstantCategories.EVENT_TYPE, "After PC Response", "PC_AFTER_RESPONSE", "After PC Response"/*Value(Shared::Triggers::Events::PC_AFTER_RESPONSE)*/),
                new NamedConstant(304, NamedConstantCategories.EVENT_TYPE, "After NPC Response", "NPC_AFTER_RESPONSE", "After NPC Response"/*Value(Shared::Triggers::Events::NPC_AFTER_RESPONSE)*/),
                new NamedConstant(305, NamedConstantCategories.EVENT_TYPE, "HI Poly Despawn", "HI_POLY_DESPAWN", "HI Poly Despawn"/*Value(Shared::Triggers::Events::HI_POLY_DESPAWN)*/),
                new NamedConstant(306, NamedConstantCategories.EVENT_TYPE, "HI Poly Despawn", "HI_POLY_DESPAWN", "HI Poly Despawn"/*Value(Shared::Triggers::Events::HI_POLY_DESPAWN)*/),
                new NamedConstant(307, NamedConstantCategories.EVENT_TYPE, "H End", "H_END", "H End"/*Value(Shared::Triggers::Events::H_END)*/),
                new NamedConstant(308, NamedConstantCategories.EVENT_TYPE, "H Start", "H_START", "H Start"/*Value(Shared::Triggers::Events::H_START)*/),
                //Moods
                new NamedConstant(191, NamedConstantCategories.MOOD, "ENERGETIC", "ENERGETIC", "ENERGETIC"/*Value(0)*/),
                new NamedConstant(192, NamedConstantCategories.MOOD, "EMBARRASSED", "EMBARRASSED", "EMBARRASSED"/*Value(1)*/),
                new NamedConstant(193, NamedConstantCategories.MOOD, "JEALOUS", "JEALOUS", "JEALOUS"/*Value(2)*/),
                new NamedConstant(194, NamedConstantCategories.MOOD, "ANGRY", "ANGRY", "ANGRY"/*Value(3)*/),
                new NamedConstant(195, NamedConstantCategories.MOOD, "SAD", "SAD", "SAD"/*Value(4)*/),
                new NamedConstant(196, NamedConstantCategories.MOOD, "RELAXED", "RELAXED", "RELAXED"/*Value(5)*/),
                new NamedConstant(197, NamedConstantCategories.MOOD, "AROUSED", "AROUSED", "AROUSED"/*Value(6)*/),
                new NamedConstant(198, NamedConstantCategories.MOOD, "SERIOUS", "SERIOUS", "SERIOUS"/*Value(7)*/),
                new NamedConstant(199, NamedConstantCategories.MOOD, "NORMAL", "NORMAL", "NORMAL"/*Value(8)*/),
                //Preferences
                new NamedConstant(200, NamedConstantCategories.PREFERENCE, "Kissing", "Kissing", "Kissing"/*Value(0)*/),
                new NamedConstant(201, NamedConstantCategories.PREFERENCE, "Breast Caress", "Breast Caress", "Breast Caress"/*Value(1)*/),
                new NamedConstant(202, NamedConstantCategories.PREFERENCE, "Vagina Caress", "Vagina Caress", "Vagina Caress"/*Value(2)*/),
                new NamedConstant(203, NamedConstantCategories.PREFERENCE, "Penis Caress", "Penis Caress", "Penis Caress"/*Value(3)*/),
                new NamedConstant(204, NamedConstantCategories.PREFERENCE, "Cunningus", "Cunningus", "Cunningus"/*Value(4)*/),
                new NamedConstant(205, NamedConstantCategories.PREFERENCE, "Fellation", "Fellation", "Fellation"/*Value(5)*/),
                new NamedConstant(206, NamedConstantCategories.PREFERENCE, "Doggy Style", "Doggy Style", "Doggy Style"/*Value(6)*/),
                new NamedConstant(207, NamedConstantCategories.PREFERENCE, "Femdom", "Femdom", "Femdom"/*Value(7)*/),
                new NamedConstant(208, NamedConstantCategories.PREFERENCE, "Anal", "Anal", "Anal"/*Value(8)*/),
                new NamedConstant(209, NamedConstantCategories.PREFERENCE, "No Condom", "No Condom", "No Condom"/*Value(9)*/),
                new NamedConstant(210, NamedConstantCategories.PREFERENCE, "Swallow", "Swallow", "Swallow"/*Value(10)*/),
                new NamedConstant(211, NamedConstantCategories.PREFERENCE, "Creampies", "Creampies", "Creampies"/*Value(11)*/),
                new NamedConstant(212, NamedConstantCategories.PREFERENCE, "Bukkake", "Bukkake", "Bukkake"/*Value(12)*/),
                //Opinions
                new NamedConstant(213, NamedConstantCategories.OPINIONS, "Together Forever", "Together Forever", "Together Forever"/*Value(4)*/),
                new NamedConstant(214, NamedConstantCategories.OPINIONS, "I'll get you", "I'll get you", "I'll get you"/*Value(5)*/),
                new NamedConstant(215, NamedConstantCategories.OPINIONS, "Unforgivable", "Unforgivable", "Unforgivable"/*Value(6)*/),
                new NamedConstant(216, NamedConstantCategories.OPINIONS, "Cheater", "Cheater", "Cheater"/*Value(7)*/),
                new NamedConstant(217, NamedConstantCategories.OPINIONS, "I hate that I...", "I hate that I...", "I hate that I..."/*Value(8)*/),
                new NamedConstant(218, NamedConstantCategories.OPINIONS, "The lowest trash...", "The lowest trash...", "The lowest trash..."/*Value(9)*/),
                new NamedConstant(219, NamedConstantCategories.OPINIONS, "Gone too far...", "Gone too far...", "Gone too far..."/*Value(10)*/),
                new NamedConstant(220, NamedConstantCategories.OPINIONS, "What shall I do next", "What shall I do next", "What shall I do next"/*Value(11)*/),
                new NamedConstant(221, NamedConstantCategories.OPINIONS, "Haven't spoken to", "Haven't spoken to", "Haven't spoken to"/*Value(12)*/),
                new NamedConstant(222, NamedConstantCategories.OPINIONS, "Don't know", "Don't know", "Don't know"/*Value(13)*/),
                new NamedConstant(223, NamedConstantCategories.OPINIONS, "Who?", "Who?", "Who?"/*Value(14)*/),
                new NamedConstant(224, NamedConstantCategories.OPINIONS, "No interest", "No interest", "No interest"/*Value(15)*/),
                new NamedConstant(225, NamedConstantCategories.OPINIONS, "I'm curious!", "I'm curious!", "I'm curious!"/*Value(16)*/),
                new NamedConstant(226, NamedConstantCategories.OPINIONS, "Wanna get back together", "Wanna get back together", "Wanna get back together"/*Value(17)*/),
                new NamedConstant(227, NamedConstantCategories.OPINIONS, "Former GF/BF", "Former GF/BF", "Former GF/BF"/*Value(18)*/),
                new NamedConstant(228, NamedConstantCategories.OPINIONS, "Let's get married", "Let's get married", "Let's get married"/*Value(19)*/),
                new NamedConstant(229, NamedConstantCategories.OPINIONS, "Mai waifu", "Mai waifu", "Mai waifu"/*Value(20)*/),
                new NamedConstant(230, NamedConstantCategories.OPINIONS, "Lover, for now", "Lover, for now", "Lover, for now"/*Value(21)*/),
                new NamedConstant(231, NamedConstantCategories.OPINIONS, "I want to break up", "I want to break up", "I want to break up"/*Value(22)*/),
                new NamedConstant(232, NamedConstantCategories.OPINIONS, "Overflowing love!", "Overflowing love!", "Overflowing love!"/*Value(23)*/),
                new NamedConstant(233, NamedConstantCategories.OPINIONS, "Angel", "Angel", "Angel"/*Value(24)*/),
                new NamedConstant(234, NamedConstantCategories.OPINIONS, "Like, but can't say it", "Like, but can't say it", "Like, but can't say it"/*Value(25)*/),
                new NamedConstant(235, NamedConstantCategories.OPINIONS, "One-Sided Love", "One-Sided Love", "One-Sided Love"/*Value(26)*/),
                new NamedConstant(236, NamedConstantCategories.OPINIONS, "No doubt it's love!", "No doubt it's love!", "No doubt it's love!"/*Value(27)*/),
                new NamedConstant(237, NamedConstantCategories.OPINIONS, "I think I like them...", "I think I like them...", "I think I like them..."/*Value(28)*/),
                new NamedConstant(238, NamedConstantCategories.OPINIONS, "Shameless!", "Shameless!", "Shameless!"/*Value(29)*/),
                new NamedConstant(239, NamedConstantCategories.OPINIONS, "Hate but love", "Hate but love", "Hate but love"/*Value(30)*/),
                new NamedConstant(240, NamedConstantCategories.OPINIONS, "Best Friend", "Best Friend", "Best Friend"/*Value(31)*/),
                new NamedConstant(241, NamedConstantCategories.OPINIONS, "Good buddies", "Good buddies", "Good buddies"/*Value(32)*/),
                new NamedConstant(242, NamedConstantCategories.OPINIONS, "Hole Brother/ Rod Sister", "Hole Brother/ Rod Sister", "Hole Brother/ Rod Sister"/*Value(33)*/),
                new NamedConstant(243, NamedConstantCategories.OPINIONS, "Friend", "Friend", "Friend"/*Value(34)*/),
                new NamedConstant(244, NamedConstantCategories.OPINIONS, "Sex Friend", "Sex Friend", "Sex Friend"/*Value(35)*/),
                new NamedConstant(245, NamedConstantCategories.OPINIONS, "Closer than friends", "Closer than friends", "Closer than friends"/*Value(36)*/),
                new NamedConstant(246, NamedConstantCategories.OPINIONS, "Normal Fags go die", "Normal Fags go die", "Normal Fags go die"/*Value(37)*/),
                new NamedConstant(247, NamedConstantCategories.OPINIONS, "Love Rival", "Love Rival", "Love Rival"/*Value(38)*/),
                new NamedConstant(248, NamedConstantCategories.OPINIONS, "Classmate", "Classmate", "Classmate"/*Value(39)*/),
                new NamedConstant(249, NamedConstantCategories.OPINIONS, "Piece of shit...", "Piece of shit...", "Piece of shit..."/*Value(40)*/),
                new NamedConstant(250, NamedConstantCategories.OPINIONS, "Fated Enemies", "Fated Enemies", "Fated Enemies"/*Value(41)*/),
                new NamedConstant(251, NamedConstantCategories.OPINIONS, "You should die", "You should die", "You should die"/*Value(42)*/),
                new NamedConstant(252, NamedConstantCategories.OPINIONS, "1000 deaths not enough", "1000 deaths not enough", "1000 deaths not enough"/*Value(43)*/),
                new NamedConstant(253, NamedConstantCategories.OPINIONS, "Love but hate", "Love but hate", "Love but hate"/*Value(44)*/),
                new NamedConstant(254, NamedConstantCategories.OPINIONS, "Physically Impossible", "Physically Impossible", "Physically Impossible"/*Value(45)*/),
                new NamedConstant(255, NamedConstantCategories.OPINIONS, "Don't want to get involved", "Don't want to get involved", "Don't want to get involved"/*Value(46)*/),
                new NamedConstant(256, NamedConstantCategories.OPINIONS, "Not good with these types", "Not good with these types", "Not good with these types"/*Value(47)*/),
                new NamedConstant(257, NamedConstantCategories.OPINIONS, "Homeroom Teacher", "Homeroom Teacher", "Homeroom Teacher"/*Value(48)*/),
                new NamedConstant(258, NamedConstantCategories.OPINIONS, "Incompetent Teacher ", "Incompetent Teacher ", "Incompetent Teacher "/*Value(49)*/),
                new NamedConstant(259, NamedConstantCategories.OPINIONS, "Ideal Teacher", "Ideal Teacher", "Ideal Teacher"/*Value(50)*/),
                new NamedConstant(260, NamedConstantCategories.OPINIONS, "Teacher I've longed for ", "Teacher I've longed for ", "Teacher I've longed for "/*Value(51)*/),
                new NamedConstant(261, NamedConstantCategories.OPINIONS, "Normal Student", "Normal Student", "Normal Student"/*Value(52)*/),
                new NamedConstant(262, NamedConstantCategories.OPINIONS, "Problem Student", "Problem Student", "Problem Student"/*Value(53)*/),
                new NamedConstant(263, NamedConstantCategories.OPINIONS, "Favorite Student ", "Favorite Student ", "Favorite Student "/*Value(54)*/),
                new NamedConstant(264, NamedConstantCategories.OPINIONS, "Special Student", "Special Student", "Special Student"/*Value(55)*/),
                new NamedConstant(265, NamedConstantCategories.OPINIONS, "Forbidden Relationship", "Forbidden Relationship", "Forbidden Relationship"/*Value(56)*/),
                new NamedConstant(266, NamedConstantCategories.OPINIONS, "Secret Relationship", "Secret Relationship", "Secret Relationship"/*Value(57)*/),
                new NamedConstant(267, NamedConstantCategories.OPINIONS, "Makes my heart throb", "Makes my heart throb", "Makes my heart throb"/*Value(58)*/),
                new NamedConstant(268, NamedConstantCategories.OPINIONS, "Really pisses me off", "Really pisses me off", "Really pisses me off"/*Value(59)*/),
                new NamedConstant(269, NamedConstantCategories.OPINIONS, "( •᷄ὤ•᷅)", "( •᷄ὤ•᷅)", "( •᷄ὤ•᷅)"/*Value(60)*/),
                new NamedConstant(270, NamedConstantCategories.OPINIONS, "Really wanna fuck", "Really wanna fuck", "Really wanna fuck"/*Value(61)*/),
                new NamedConstant(271, NamedConstantCategories.OPINIONS, "Slut", "Slut", "Slut"/*Value(62)*/),
                new NamedConstant(272, NamedConstantCategories.OPINIONS, "Lewd Promise", "Lewd Promise", "Lewd Promise"/*Value(63)*/),
                new NamedConstant(273, NamedConstantCategories.OPINIONS, "Good Chemistry", "Good Chemistry", "Good Chemistry"/*Value(64)*/),
                new NamedConstant(274, NamedConstantCategories.OPINIONS, "Death flag for lover cheating", "Death flag for lover cheating", "Death flag for lover cheating"/*Value(65)*/),
                new NamedConstant(275, NamedConstantCategories.OPINIONS, "Inactive with > 600 love, active otherwise", "Inactive with > 600 love, active otherwise", "Inactive with > 600 love, active otherwise"/*Value(66)*/),
                new NamedConstant(276, NamedConstantCategories.OPINIONS, "Seat number of the card their lover cheated with", "Seat number of the card their lover cheated with", "Seat number of the card their lover cheated with"/*Value(67)*/),
                new NamedConstant(277, NamedConstantCategories.OPINIONS, "Opinion65", "Opinion65", "Opinion65"/*Value(68)*/),
                new NamedConstant(278, NamedConstantCategories.OPINIONS, "Witnessed target card having public H", "Witnessed target card having public H", "Witnessed target card having public H"/*Value(69)*/),
                new NamedConstant(279, NamedConstantCategories.OPINIONS, "Witnessed partner of target card having public H", "Witnessed partner of target card having public H", "Witnessed partner of target card having public H"/*Value(70)*/),
                new NamedConstant(280, NamedConstantCategories.OPINIONS, "Active if insulted by target card at least once", "Active if insulted by target card at least once", "Active if insulted by target card at least once"/*Value(71)*/),
                new NamedConstant(281, NamedConstantCategories.OPINIONS, "Active if lost fight to target card at least once", "Active if lost fight to target card at least once", "Active if lost fight to target card at least once"/*Value(72)*/),
                new NamedConstant(282, NamedConstantCategories.OPINIONS, "Opinion70", "Opinion70", "Opinion70"/*Value(73)*/),
                new NamedConstant(282, NamedConstantCategories.OPINIONS, "Opinion70", "Opinion70", "Opinion70"/*Value(73)*/),
                new NamedConstant(283, NamedConstantCategories.OPINIONS, "Opinion71", "Opinion71", "Opinion71"/*Value(74)*/),
                new NamedConstant(284, NamedConstantCategories.OPINIONS, "Opinion72", "Opinion72", "Opinion72"/*Value(75)*/),
                new NamedConstant(285, NamedConstantCategories.OPINIONS, "Opinion73", "Opinion73", "Opinion73"/*Value(76)*/),
                new NamedConstant(286, NamedConstantCategories.OPINIONS, "Opinion74", "Opinion74", "Opinion74"/*Value(77)*/),
                new NamedConstant(287, NamedConstantCategories.OPINIONS, "Active if slapped by target card at least once", "Active if slapped by target card at least once", "Active if slapped by target card at least once"/*Value(78)*/),
                new NamedConstant(288, NamedConstantCategories.OPINIONS, "0 if this is a fresh class, 1 otherwise", "0 if this is a fresh class, 1 otherwise", "0 if this is a fresh class, 1 otherwise"/*Value(79)*/),
                new NamedConstant(289, NamedConstantCategories.OPINIONS, "Opinion77", "Opinion77", "Opinion77"/*Value(80)*/),
                new NamedConstant(290, NamedConstantCategories.OPINIONS, "Opinion78", "Opinion78", "Opinion78"/*Value(81)*/),
                new NamedConstant(291, NamedConstantCategories.OPINIONS, "Opinion79", "Opinion79", "Opinion79"/*Value(82)*/),
                new NamedConstant(292, NamedConstantCategories.OPINIONS, "Opinion80", "Opinion80", "Opinion80"/*Value(83)*/),
                new NamedConstant(293, NamedConstantCategories.OPINIONS, "Opinion81", "Opinion81", "Opinion81"/*Value(84)*/),
                new NamedConstant(294, NamedConstantCategories.OPINIONS, "Opinion82", "Opinion82", "Opinion82"/*Value(85)*/),
                new NamedConstant(295, NamedConstantCategories.OPINIONS, "Opinion83", "Opinion83", "Opinion83"/*Value(86)*/),
                new NamedConstant(296, NamedConstantCategories.OPINIONS, "Opinion84", "Opinion84", "Opinion84"/*Value(87)*/),
                new NamedConstant(297, NamedConstantCategories.OPINIONS, "Opinion85", "Opinion85", "Opinion85"/*Value(88)*/),
                // Rooms
                new NamedConstant(298, NamedConstantCategories.ROOM, "School gates", "School gates", "School gates"/* Value(0) */),
                new NamedConstant(299, NamedConstantCategories.ROOM, "Back street", "Back street", "Back street"/* Value(1) */),
                new NamedConstant(300, NamedConstantCategories.ROOM, "Outside gymnasium", "Outside gymnasium", "Outside gymnasium"/* Value(2) */),
                new NamedConstant(301, NamedConstantCategories.ROOM, "School route", "School route", "School route"/* Value(3) */),
                new NamedConstant(302, NamedConstantCategories.ROOM, "Boys' changing room", "Boys' changing room", "Boys' changing room"/* Value(4) */),
                new NamedConstant(303, NamedConstantCategories.ROOM, "Girls' changing room", "Girls' changing room", "Girls' changing room"/* Value(5) */),
                new NamedConstant(304, NamedConstantCategories.ROOM, "Boys' shower", "Boys' shower", "Boys' shower"/* Value(6) */),
                new NamedConstant(305, NamedConstantCategories.ROOM, "Girls' shower", "Girls' shower", "Girls' shower"/* Value(7) */),
                new NamedConstant(306, NamedConstantCategories.ROOM, "Lockers", "Lockers", "Lockers"/* Value(8) */),
                new NamedConstant(307, NamedConstantCategories.ROOM, "Outside teachers lounge", "Outside lounge", "Outside lounge"/* Value(9) */),
                new NamedConstant(308, NamedConstantCategories.ROOM, "Outside toilets", "Outside toilets", "Outside toilets"/* Value(10) */),
                new NamedConstant(309, NamedConstantCategories.ROOM, "Outside classroom", "Outside classroom", "Outside classroom"/* Value(11) */),
                new NamedConstant(310, NamedConstantCategories.ROOM, "Rooftop access", "Rooftop access", "Rooftop access"/* Value(12) */),
                new NamedConstant(311, NamedConstantCategories.ROOM, "Old building 1st floor", "Old building 1st floor", "Old building 1st floor"/* Value(13) */),
                new NamedConstant(312, NamedConstantCategories.ROOM, "Old building 2nd floor", "Old building 2nd floor", "Old building 2nd floor"/* Value(14) */),
                new NamedConstant(313, NamedConstantCategories.ROOM, "Old building 3rd floor", "Old building 3rd floor", "Old building 3rd floor"/* Value(15) */),
                new NamedConstant(314, NamedConstantCategories.ROOM, "Teachers lounge", "Teachers lounge", "Teachers lounge"/* Value(16) */),
                new NamedConstant(315, NamedConstantCategories.ROOM, "Infirmary", "Infirmary", "Infirmary"/* Value(17) */),
                new NamedConstant(316, NamedConstantCategories.ROOM, "Library", "Library", "Library"/* Value(18) */),
                new NamedConstant(317, NamedConstantCategories.ROOM, "Classroom", "Classroom", "Classroom"/* Value(19) */),
                new NamedConstant(318, NamedConstantCategories.ROOM, "Boys' Toilets", "Boys' Toilets", "Boys' Toilets"/* Value(20) */),
                new NamedConstant(319, NamedConstantCategories.ROOM, "Girls' Toilets", "Girls' Toilets", "Girls' Toilets"/* Value(21) */),
                new NamedConstant(320, NamedConstantCategories.ROOM, "Rooftop", "Rooftop", "Rooftop"/* Value(22) */),
                new NamedConstant(321, NamedConstantCategories.ROOM, "Outside counsel", "Outside counsel", "Outside counsel"/* Value(23) */),
                new NamedConstant(322, NamedConstantCategories.ROOM, "Outside cafeteria", "Outside cafeteria", "Outside cafeteria"/* Value(24) */),
                new NamedConstant(323, NamedConstantCategories.ROOM, "Courtyard", "Courtyard", "Courtyard"/* Value(25) */),
                new NamedConstant(324, NamedConstantCategories.ROOM, "2nd floor hallway", "2nd floor hallway", "2nd floor hallway"/* Value(26) */),
                new NamedConstant(325, NamedConstantCategories.ROOM, "3rd floor passage", "3rd floor passage", "3rd floor passage"/* Value(27) */),
                new NamedConstant(326, NamedConstantCategories.ROOM, "Swimming pool", "Swimming pool", "Swimming pool"/* Value(28) */),
                new NamedConstant(327, NamedConstantCategories.ROOM, "Track", "Track", "Track"/* Value(29) */),
                new NamedConstant(328, NamedConstantCategories.ROOM, "Baseball field", "Baseball field", "Baseball field"/* Value(30) */),
                new NamedConstant(329, NamedConstantCategories.ROOM, "Dojo", "Dojo", "Dojo"/* Value(31) */),
                new NamedConstant(330, NamedConstantCategories.ROOM, "Gymnasium", "Gymnasium", "Gymnasium"/* Value(32) */),
                new NamedConstant(331, NamedConstantCategories.ROOM, "Arts room", "Arts room", "Arts room"/* Value(33) */),
                new NamedConstant(332, NamedConstantCategories.ROOM, "Multipurpose room", "Multipurpose room", "Multipurpose room"/* Value(34) */),
                new NamedConstant(333, NamedConstantCategories.ROOM, "Japanese room", "Japanese room", "Japanese room"/* Value(35) */),
                new NamedConstant(334, NamedConstantCategories.ROOM, "Behind Dojo", "Behind Dojo", "Behind Dojo"/* Value(36) */),
                new NamedConstant(335, NamedConstantCategories.ROOM, "Outside Dojo", "Outside Dojo", "Outside Dojo"/* Value(37) */),
                new NamedConstant(336, NamedConstantCategories.ROOM, "Cafeteria", "Cafeteria", "Cafeteria"/* Value(38) */),
                new NamedConstant(337, NamedConstantCategories.ROOM, "Outside Station", "Outside Station", "Outside Station"/* Value(39) */),
                new NamedConstant(338, NamedConstantCategories.ROOM, "Karaoke", "Karaoke", "Karaoke"/* Value(40) */),
                new NamedConstant(339, NamedConstantCategories.ROOM, "Boys' night room", "Boys' night room", "Boys' night room - might not be a thing"/* Value(41) */),
                new NamedConstant(340, NamedConstantCategories.ROOM, "Girls' night room", "Girls' night room", "Girls' night room - might not be a thing"/* Value(42) */),
                new NamedConstant(341, NamedConstantCategories.ROOM, "Boys' room", "Boys' room", "Boys' room"/* Value(43) */),
                new NamedConstant(342, NamedConstantCategories.ROOM, "Girls' room", "Girls' room", "Girls' room"/* Value(44) */),
                new NamedConstant(343, NamedConstantCategories.ROOM, "Boys' shower stall", "Boys' shower stall", "Boys' shower stall"/* Value(45) */),
                new NamedConstant(344, NamedConstantCategories.ROOM, "Girls' shower stall", "Girls' shower stall", "Girls' shower stall"/* Value(46) */),
                new NamedConstant(345, NamedConstantCategories.ROOM, "Boys' toilet stall", "Boys' toilet stall", "Boys' toilet stall"/* Value(47) */),
                new NamedConstant(346, NamedConstantCategories.ROOM, "Girls' toilet stall", "Girls' toilet stall", "Girls' toilet stall"/* Value(48) */),
                new NamedConstant(347, NamedConstantCategories.ROOM, "Counseling room", "Counseling room", "Counseling room"/* Value(49) */),
                new NamedConstant(348, NamedConstantCategories.ROOM, "Gym storeroom", "Gym storeroom", "Gym storeroom"/* Value(50) */),
                new NamedConstant(349, NamedConstantCategories.ROOM, "Love Hotel", "Love Hotel", "Love Hotel"/* Value(51) */),
                new NamedConstant(350, NamedConstantCategories.ROOM, "Machine room", "Machine room", "Machine room"/* Value(52) */),
                new NamedConstant(351, NamedConstantCategories.CONVERSATIONS, "MINNA_PLAY", "MINNA_EAT", "MINNA_EAT"/* Value(ExtClass::ConversationId::MINNA_PLAY) */),
                new NamedConstant(352, NamedConstantCategories.TIME_PERIOD, "HOMEROOM", "HOMEROOM", "HOMEROOM"/* Value(ExtClass::PeriodId::HOMEROOM) */),
                new NamedConstant(352, NamedConstantCategories.TIME_PERIOD, "EXAM", "EXAM", "EXAM"/* Value(ExtClass::PeriodId::EXAM) */),
            },
            {
                // BOOL
            },
            {
                // FLOAT
            },
            {
                // STRING
            }
        };

    @Override
    public String toString() {
        return interactiveName;
    }

    public static NamedConstant FromId(Value.Types type, int id){
        for(int i = 0;i < g_NamedConstants[type.ordinal()].length;i++){
            if(g_NamedConstants[type.ordinal()][i].id == id){
                return g_NamedConstants[type.ordinal()][i];
            }
        }
        if(id < 1 || id > g_NamedConstants[type.ordinal()].length) return null;
        return g_NamedConstants[type.ordinal()][id-1];
    }

    private enum NamedConstantCategories{
        RELATIONSHIP("Relationship"),
        CONVERSATIONS("Conversation"),
        TRAIT("Trait"),
        TIME_DAY("Time (DAy)"),
        TIME_PERIOD("Time (Period)"),
        CHAR_PREG_RISK("Character (Pregnancy Risk)"),
        EVENT_TYPE("Event Type"),
        MOOD("Mood"),
        PREFERENCE("Preferences"),
        OPINIONS("Opinions"),
        ROOM("Room");
        private final String name;
        NamedConstantCategories(String name){
            this.name = name;
        }
    }
}
